### ISSUE TITLE
Getting "logger.error is not a function" after upgrading to pm2-metrics 1.0.15

### ISSUE THREAD

**Issue by fllaca** [saikatharryc/pm2-prometheus-exporter#11]
1.0.15 seems to be broken. Logs:

```[TAILING] Tailing last 15 lines for [pm2-metrics] process (change the value with --lines option)                                                       
/home/adhara/.pm2/logs/pm2-metrics-out.log last 15 lines:
15|pm2-met | pm2-prometheus-exporter listening at 0.0.0.0:9209
15|pm2-met | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
15|pm2-met | pm2-prometheus-exporter listening at 0.0.0.0:9209
15|pm2-met | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:

/home/adhara/.pm2/logs/pm2-metrics-error.log last 15 lines:
15|pm2-met |     at pm2c.then.catch.err (/home/adhara/.pm2/modules/pm2-metrics/node_modules/pm2-metrics/exporter.js:111:14)
15|pm2-met |     at process._tickCallback (internal/process/next_tick.js:68:7)
15|pm2-met | (node:22894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 42)
15|pm2-met | (node:22894) UnhandledPromiseRejectionWarning: TypeError: logger.error is not a function
15|pm2-met |     at pm2c.then.catch.err (/home/adhara/.pm2/modules/pm2-metrics/node_modules/pm2-metrics/exporter.js:111:14)
15|pm2-met |     at process._tickCallback (internal/process/next_tick.js:68:7)
15|pm2-met | (node:22894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)
15|pm2-met | TypeError: logger.error is not a function
15|pm2-met |     at pm2c.then.catch.err (/home/adhara/.pm2/modules/pm2-metrics/node_modules/pm2-metrics/exporter.js:111:14)
15|pm2-met |     at process._tickCallback (internal/process/next_tick.js:68:7)
15|pm2-met | (node:32727) UnhandledPromiseRejectionWarning: TypeError: logger.error is not a function
15|pm2-met |     at pm2c.then.catch.err (/home/adhara/.pm2/modules/pm2-metrics/node_modules/pm2-metrics/exporter.js:111:14)
15|pm2-met |     at process._tickCallback (internal/process/next_tick.js:68:7)
15|pm2-met | (node:32727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
15|pm2-met | (node:32727) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by saikatharryc** [comment]
@fllaca  Hi you can either use the `1.0.14` or else `1.0.16` . if you are still in .`1.0.15` please upgrade or degrade.
