### ISSUE TITLE
error "set" of undefined

### ISSUE THREAD

**Issue by reyhansofian** [saikatharryc/pm2-prometheus-exporter#2]
I'm using pm2 version 3.2.8. After install this package, I got this error on my pm2 log

```
TypeError: Cannot read property 'set' of undefined
    at Object.keys.forEach.k (/opt/kata/pm2-prometheus-exporter/exporter.js:88:17)
    at Array.forEach (<anonymous>)
    at list.forEach.p (/opt/kata/pm2-prometheus-exporter/exporter.js:85:29)
    at Array.forEach (<anonymous>)
    at pm2c.then.list (/opt/kata/pm2-prometheus-exporter/exporter.js:35:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

after some investigation, there are 2 new metrics that are not mapped yet. Those metrics are `prev_restart_delay` and `pm2_event_loop_latency`

**Comment by saikatharryc** [comment]
the new npm version will be `1.0.10` and will be available for download withing 5-10 minutes, 
check here:
https://www.npmjs.com/package/pm2-metrics

Thanks for the PR & Issue
