### ISSUE TITLE
Error at exporter.js Value is not a valid number

### ISSUE THREAD

**Issue by AlithAnar** [saikatharryc/pm2-prometheus-exporter#41]
Hi, my pm2-metrics module suddenly stopped exporting data. I've checked logs and this is what I see:

```
{"level":50,"time":1583744139131,"pid":629,"hostname":"2ba2701777fc","msg":"Value is not a valid number: 0","stack":"TypeError: Value is not a valid number: 0\n    at /root/.pm2/modules/pm2-metrics/node_modules/prom-client/lib/gauge.js:228:10\n    at Gauge.set (/root/.pm2/modules/pm2-metrics/node_modules/prom-client/lib/gauge.js:91:32)\n    at /root/.pm2/modules/pm2-metrics/node_modules/pm2-metrics/exporter.js:111:17\n    at Array.forEach (<anonymous>)\n    at /root/.pm2/modules/pm2-metrics/node_modules/pm2-metrics/exporter.js:102:29\n    at Array.forEach (<anonymous>)\n    at /root/.pm2/modules/pm2-metrics/node_modules/pm2-metrics/exporter.js:44:12\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","type":"Error","v":1}
```

**Comment by saikatharryc** [comment]
Hi @AlithAnar , You can now use pm2-metrics@1.0.33 or grater version, 
it's solved in pm2-metrics@1.0.33.
